### ISSUE TITLE
Space reduction

### ISSUE THREAD

**Issue by raybellis** [benheck/attiny10_game#2]
I've found I can save 22 bytes (11 instructions) of program space by declaring the `gameOver` and `drawPF` functions as `static`, allowing the compiler to "inline" those functions.

This should also reduce stack usage, allowing more valuable RAM to be used.  I haven't calculated that completely, but `drawPF` alone uses four stack bytes, which are saved otherwise.

**Comment by benheck** [comment]
Nice!

**Comment by raybellis** [comment]
closed by #3
